<?php
// In D7 this is changed to hook_user_login()
function islandora_pid_list_user($op, &$edit, &$account, $category = NULL) {
  module_load_include('inc', 'islandora_pid_list', 'pidlist');
  if ($op == 'login') {
    if (!empty($_SESSION['islandora_pid_list'])) {
       foreach($_SESSION['islandora_pid_list'] as $key => $value)
       {
        $pidlistsession = unserialize($value);
        $pidlistsession->set_session(FALSE);
        $pidlistsession->create_list();
        unset($_SESSION['islandora_pid_list'][$key]);
       }
    }
  }
}

function islandora_pid_list_menu() {
$items['pidlist'] = array (
  'title' => 'Islandora Pid List',
  'description' => "Track and manage list of pids",
  'type' => MENU_NORMAL_ITEM,
  'page callback' => 'drupal_get_form',
  'page arguments' => array('islandora_pid_list_list_form'),
  'access arguments' => array('access content'),
  'file' => 'pid_list_form.inc',
);

$items['pidlist/lists'] = array (
  'title' => 'Lists',
  'type' => MENU_DEFAULT_LOCAL_TASK,
  'page callback' => 'drupal_get_form',
  'page arguments' => array('islandora_pid_list_list_form'),
  'access arguments' => array('access content'),
  'file' => 'pid_list_form.inc'
);

$items['pidlist/add'] = array (
  'title' => 'Add',
  'type' => MENU_LOCAL_TASK,
  'page callback' => 'drupal_get_form',
  'page arguments' => array('islandora_pid_list_add_form'),
  'access arguments' => array('access content'),
  'file' => 'pid_list_form.inc'
  );
return $items;
}









